# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    git remote add github https://vishnuprasad-ejyothi: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@github.com/vishnuprasad-ejyothi/PowerApp-Integration.git 
    git push github dev
  displayName: 'Run a multi-line script'
