# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    git remote add github https://github.com/vishnuprasad-ejyothi/PowerApp-Integration.git 
    git push --mirror github
  displayName: 'Run a multi-line script'
